(()=>{'use strict';
const $=id=>document.getElementById(id);
const EVENT_CACHE_MS=6*60*60*1000;
const SYMBOL_MAP={MUV2:'MUV2.DE'};
let eventRequest=false;

function ensureStyles(){const s=document.createElement('style');s.textContent=`
.event-card{border-color:rgba(255,159,10,.28);background:linear-gradient(145deg,rgba(255,159,10,.07),var(--card) 60%)}
.event-top{display:flex;align-items:flex-start;justify-content:space-between;gap:10px}.event-badge{padding:6px 9px;border-radius:999px;border:1px solid var(--line);font-size:10px;font-weight:900;color:var(--muted);white-space:nowrap}
.event-badge.low{color:var(--green);border-color:rgba(48,209,88,.35);background:rgba(48,209,88,.08)}.event-badge.medium{color:var(--yellow);border-color:rgba(255,214,10,.35);background:rgba(255,214,10,.07)}.event-badge.high,.event-badge.error{color:var(--red);border-color:rgba(255,69,58,.38);background:rgba(255,69,58,.09)}
.event-hero{margin-top:12px;padding:13px;border-radius:13px;border:1px solid var(--line);background:var(--card2)}.event-hero.low{border-color:rgba(48,209,88,.28)}.event-hero.medium{border-color:rgba(255,214,10,.3)}.event-hero.high,.event-hero.error{border-color:rgba(255,69,58,.32)}
.event-title{font-size:17px;font-weight:900}.event-sub{color:var(--muted);font-size:11px;line-height:1.45;margin-top:5px}.event-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px}.event-cell{padding:10px;border:1px solid var(--line);border-radius:11px;background:var(--card2)}.event-cell span{display:block;color:var(--muted);font-size:10px;margin-bottom:4px}.event-cell strong{font-size:13px}.event-actions{display:grid;grid-template-columns:1fr auto;gap:8px;margin-top:10px}.event-message{padding:10px 11px;border:1px solid var(--line);border-radius:11px;background:var(--card2);color:var(--muted);font-size:11px;line-height:1.4}.event-refresh{min-width:46px;border:1px solid var(--line);border-radius:11px;background:var(--card2);color:var(--blue);font-weight:900}@media(max-width:380px){.event-grid{grid-template-columns:1fr}}
`;document.head.appendChild(s)}

function buildCard(){const live=$('livePrice')?.closest('section');if(!live||$('eventCard'))return;const card=document.createElement('section');card.id='eventCard';card.className='card event-card';card.innerHTML=`<div class="event-top"><div><h2 style="margin:0;font-size:17px">Stock Intelligence</h2><p class="mini">Finnhub · Earnings & Event Risk</p></div><span id="eventBadge" class="event-badge">—</span></div><div id="eventHero" class="event-hero"><div id="eventTitle" class="event-title">Earnings werden geprüft …</div><div id="eventSub" class="event-sub">Ausgewählte Aktie: —</div></div><div class="event-grid"><div class="event-cell"><span>Nächste Earnings</span><strong id="eventDate">—</strong></div><div class="event-cell"><span>Countdown</span><strong id="eventCountdown">—</strong></div><div class="event-cell"><span>Zeitpunkt</span><strong id="eventHour">—</strong></div><div class="event-cell"><span>EPS Estimate</span><strong id="eventEps">—</strong></div><div class="event-cell"><span>Revenue Estimate</span><strong id="eventRevenue">—</strong></div><div class="event-cell"><span>Letzte Earnings</span><strong id="eventLast">—</strong></div></div><div class="event-actions"><div id="eventMessage" class="event-message">Warte auf Finnhub-Key …</div><button id="eventRefresh" class="event-refresh">↻</button></div>`;live.insertAdjacentElement('afterend',card);$('eventRefresh').addEventListener('click',()=>loadEvents(true))}

function apiKey(){return localStorage.getItem('tradecalc-finnhub-key')||''}function ticker(){return $('stock')?.value||'GOOG'}function apiTicker(t){return SYMBOL_MAP[t]||t}function isInternational(t){return t==='MUV2'||/[.]/.test(apiTicker(t))}function cacheKey(t){return'tradecalc-earnings-v2-'+t}function getCache(t){try{return JSON.parse(localStorage.getItem(cacheKey(t))||'null')}catch{return null}}function setCache(t,data){try{localStorage.setItem(cacheKey(t),JSON.stringify({time:Date.now(),data}))}catch{}}
function iso(d){return d.toISOString().slice(0,10)}function addDays(d,n){return new Date(d.getTime()+n*86400000)}function daysUntil(s){const a=new Date(),b=new Date(s+'T12:00:00');a.setHours(12,0,0,0);return Math.round((b-a)/86400000)}function hourText(h){return h==='bmo'?'Vor Börsenöffnung':h==='amc'?'Nach Börsenschluss':h==='dmh'?'Während Börsenhandel':h||'Nicht angegeben'}function revenue(v){const x=Number(v);if(!Number.isFinite(x))return'—';if(Math.abs(x)>=1e9)return(x/1e9).toLocaleString('de-DE',{maximumFractionDigits:2})+' Mrd.';if(Math.abs(x)>=1e6)return(x/1e6).toLocaleString('de-DE',{maximumFractionDigits:1})+' Mio.';return x.toLocaleString('de-DE',{maximumFractionDigits:0})}
function updateUsage(){try{const now=Date.now(),a=JSON.parse(localStorage.getItem('tradecalc-api-reqs')||'[]').filter(x=>now-x<60000);localStorage.setItem('tradecalc-api-reqs',JSON.stringify(a));if($('apiUsage'))$('apiUsage').textContent=a.length+' / 10 Requests · letzte 60 s'}catch{}}function allowRequest(){try{const now=Date.now(),a=JSON.parse(localStorage.getItem('tradecalc-api-reqs')||'[]').filter(x=>now-x<60000);if(a.length>=10)return false;a.push(now);localStorage.setItem('tradecalc-api-reqs',JSON.stringify(a));updateUsage();return true}catch{return true}}
function clearFields(){['eventDate','eventCountdown','eventHour','eventEps','eventRevenue','eventLast'].forEach(id=>{if($(id))$(id).textContent='—'})}
function showNoData(t,last){clearFields();$('eventHero').className='event-hero';$('eventBadge').className='event-badge';$('eventBadge').textContent='KEIN TERMIN';$('eventTitle').textContent='⚪ Keine kommenden Earnings gefunden';$('eventSub').textContent=t+' · Finnhub hat aktuell keinen bestätigten zukünftigen Termin geliefert.';$('eventLast').textContent=last||'—'}
function showError(t,msg,detail){clearFields();$('eventHero').className='event-hero error';$('eventBadge').className='event-badge error';$('eventBadge').textContent='API FEHLER';$('eventTitle').textContent='🔴 Earnings-Abruf fehlgeschlagen';$('eventSub').textContent=t+' · '+msg;$('eventMessage').textContent=detail||msg}
function showData(t,data,cached=false){const arr=Array.isArray(data?.earningsCalendar)?data.earningsCalendar:[],today=iso(new Date()),future=arr.filter(x=>x.date>=today).sort((a,b)=>a.date.localeCompare(b.date)),next=future[0]||null,last=data?.lastPeriod||'';if(!next){showNoData(t,last);$('eventMessage').textContent=(cached?'Cache · ':'')+'Abruf erfolgreich, aber kein kommender Termin vorhanden.';return}const d=daysUntil(next.date);let level='low',icon='🟢',label='LOW';if(d<=1){level='high';icon='🔴';label='HIGH'}else if(d<=7){level='medium';icon='🟡';label='MEDIUM'}$('eventHero').className='event-hero '+level;$('eventBadge').className='event-badge '+level;$('eventBadge').textContent='EVENT RISK '+label;$('eventTitle').textContent=icon+' Earnings '+(d===0?'heute':d===1?'morgen':'in '+d+' Tagen');$('eventSub').textContent=t+' · '+next.date+' · '+hourText(next.hour);$('eventDate').textContent=next.date||'—';$('eventCountdown').textContent=d===0?'Heute':d===1?'1 Tag':d+' Tage';$('eventHour').textContent=hourText(next.hour);$('eventEps').textContent=Number.isFinite(Number(next.epsEstimate))?Number(next.epsEstimate).toLocaleString('de-DE',{maximumFractionDigits:3}):'—';$('eventRevenue').textContent=revenue(next.revenueEstimate);$('eventLast').textContent=last||'—';$('eventMessage').textContent=(cached?'Cache · ':'')+arr.length+' Earnings-Einträge geladen.'}

async function requestJson(url){if(!allowRequest())throw new Error('SAFE_LIMIT');let r;try{r=await fetch(url,{cache:'no-store'})}catch{throw new Error('NETWORK')}let bodyText='';try{bodyText=await r.text()}catch{}let data={};try{data=bodyText?JSON.parse(bodyText):{}}catch{}if(!r.ok)throw new Error('HTTP_'+r.status+(data?.error?':'+data.error:''));if(data?.error)throw new Error('API:'+data.error);return data}
async function futureCalendar(key,mapped,international,days){const now=new Date(),params=new URLSearchParams({from:iso(now),to:iso(addDays(now,days)),symbol:mapped,token:key});if(international)params.set('international','true');return requestJson('https://finnhub.io/api/v1/calendar/earnings?'+params.toString())}
async function lastEarnings(key,mapped){try{const d=await requestJson('https://finnhub.io/api/v1/stock/earnings?symbol='+encodeURIComponent(mapped)+'&limit=1&token='+encodeURIComponent(key));return Array.isArray(d)&&d[0]?.period?d[0].period:''}catch{return''}}

async function loadEvents(force=false){if(!$('eventCard'))return;const t=ticker(),key=apiKey(),mapped=apiTicker(t),cache=getCache(mapped);$('eventSub').textContent='Ausgewählte Aktie: '+t;if(!key){showError(t,'Finnhub-Key fehlt','Öffne hier im Rechner ⚙️ API und speichere den bestehenden Key.');return}if(!force&&cache&&Date.now()-cache.time<EVENT_CACHE_MS){showData(t,cache.data,true);return}if(eventRequest)return;eventRequest=true;$('eventMessage').textContent='Earnings werden geladen …';$('eventTitle').textContent='Earnings werden geprüft …';try{let cal;try{cal=await futureCalendar(key,mapped,isInternational(t),180)}catch(e){if(/^HTTP_(403|422)|^API:/.test(e.message))cal=await futureCalendar(key,mapped,isInternational(t),45);else throw e}const last=await lastEarnings(key,mapped),data={earningsCalendar:Array.isArray(cal?.earningsCalendar)?cal.earningsCalendar:[],lastPeriod:last};setCache(mapped,data);showData(t,data,false)}catch(e){const m=String(e.message||e);if(m==='SAFE_LIMIT')showError(t,'Safe-Mode-Limit erreicht','Kurz warten und erneut versuchen.');else if(m==='NETWORK')showError(t,'Netzwerk/CORS-Fehler','Der Browser konnte den Finnhub-Earnings-Endpunkt nicht erreichen.');else if(m.includes('429'))showError(t,'Finnhub-Limit 429','Kurz warten und erneut versuchen.');else if(m.includes('403')||m.startsWith('API:'))showError(t,'Finnhub-Zugriff abgewiesen',m.replace(/^API:/,''));else showError(t,'Finnhub-Antwort '+m,m)}finally{eventRequest=false;updateUsage()}}

function init(){ensureStyles();buildCard();const stock=$('stock');if(stock)stock.addEventListener('change',()=>setTimeout(()=>loadEvents(false),50));const save=$('saveKey');if(save)save.addEventListener('click',()=>setTimeout(()=>loadEvents(true),250));const refresh=$('refreshLive');if(refresh)refresh.addEventListener('click',()=>loadEvents(false));loadEvents(false)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();