(()=>{'use strict';
const V='1.0',KEY='senseis-focus-engine-v1',FK='tradecalc-finnhub-key',SEL='senseis-stock-intelligence-symbol';
const ENTER=85,STAY=70,MIN_STAY=7*864e5,COOLDOWN=7*864e5,DELAY=2600;
let db=read(),open=false,running=false,stop=false,paintBusy=false,timer=0;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],cl=(v,a=0,b=100)=>Math.max(a,Math.min(b,Number(v)||0)),n=v=>Number.isFinite(Number(v))?Number(v):null;
const sym=v=>String(v||'').trim().toUpperCase().replace(/\.DE$/,''),esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=(v,d=0)=>n(v)==null?'—':n(v).toLocaleString('de-DE',{maximumFractionDigits:d}),pct=(v,d=0)=>n(v)==null?'—':`${n(v)>0?'+':''}${fmt(v,d)} %`;
function read(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');if(x)return{entries:x.entries||{},snapshots:x.snapshots||{},lastScan:x.lastScan||0}}catch{}return{entries:{},snapshots:{},lastScan:0}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(db))}catch{}}
function pick(m,keys){m=m?.metric||m||{};for(const k of keys){const v=n(m[k]);if(v!=null)return v}const map=new Map(Object.entries(m).map(([k,v])=>[k.toLowerCase(),v]));for(const k of keys){const v=n(map.get(k.toLowerCase()));if(v!=null)return v}return null}
function weighted(parts){let t=0,w=0;for(const [v,x] of parts){if(v==null)continue;t+=cl(v)*x;w+=x}return w?Math.round(t/w):null}
function linear(v,a,b){v=n(v);return v==null?null:cl((v-a)/(b-a)*100)}
function low(v,best,worst){v=n(v);return v==null?null:cl((worst-v)/(worst-best)*100)}
function pe(v){v=n(v);if(v==null)return null;if(v<=0)return 10;if(v<8)return 45;if(v<=18)return 90;if(v<=25)return 78;if(v<=35)return 55;if(v<=50)return 32;return 15}
function beta(v){v=n(v);if(v==null)return null;if(v<=1.15)return 90;if(v<=1.5)return 70;if(v<=2)return 45;return 20}
function activeContext(t){try{const o=$('#tradeToolsFrame')?.contentDocument,d=o?.getElementById('calcFrame')?.contentDocument;if(sym(d?.getElementById('stock')?.value)===t)return true;const p=JSON.parse(localStorage.getItem('tradecalc-last-import')||'null');return sym(p?.symbol)===t&&p?.entry!=null&&p?.sl!=null}catch{return false}}
function history(t,peNow){const rows=db.snapshots[t]||[],vals=rows.map(x=>n(x.pe)).filter(x=>x>0);if(vals.length<20||!(peNow>0))return{status:'WARMING_UP',count:vals.length,p:null};vals.sort((a,b)=>a-b);return{status:'READY',count:vals.length,p:Math.round(vals.filter(x=>x<=peNow).length/vals.length*100)}}
function snapshot(e){const rows=(db.snapshots[e.ticker]||[]).filter(x=>x.date!==new Date().toISOString().slice(0,10));rows.push({date:new Date().toISOString().slice(0,10),price:e.price,pe:e.metrics.pe,drawdown:e.drawdown,gapPct:e.gap?.gapPct??null,focusScore:e.focusScore});db.snapshots[e.ticker]=rows.slice(-120)}
function score(item,q,raw){const t=sym(item.symbol),m={pe:pick(raw,['peBasicExclExtraTTM','peTTM']),roe:pick(raw,['roeTTM','roeAnnual']),margin:pick(raw,['netProfitMarginTTM','netProfitMarginAnnual']),gross:pick(raw,['grossMarginTTM','grossMarginAnnual']),rev:pick(raw,['revenueGrowthTTMYoy','revenueGrowth3Y']),eps:pick(raw,['epsGrowthTTMYoy','epsGrowth3Y']),cur:pick(raw,['currentRatioQuarterly','currentRatioAnnual']),de:pick(raw,['totalDebt/totalEquityQuarterly','totalDebt/totalEquityAnnual']),beta:pick(raw,['beta']),hi:pick(raw,['52WeekHigh']),lo:pick(raw,['52WeekLow']),cap:pick(raw,['marketCapitalization']),fcf:pick(raw,['freeCashFlowMarginTTM','freeCashFlowMarginAnnual']),atr:pick(raw,['atr14','atr'])};
const price=n(q.c),pos=price!=null&&m.hi>m.lo?cl((price-m.lo)/(m.hi-m.lo)*100):null,dd=price!=null&&m.hi>0?(price/m.hi-1)*100:null,h=history(t,m.pe);
const quality=weighted([[linear(m.roe,5,30),25],[linear(m.margin,0,25),22],[linear(m.gross,15,65),12],[linear(m.cur,.8,2.2),12],[linear(m.fcf,0,20),14],[m.cap==null?null:linear(Math.log10(Math.max(m.cap,1)),3,6),15]]),growth=weighted([[linear(m.rev,-5,20),55],[linear(m.eps,-10,25),45]]),risk=weighted([[low(m.de,30,250),45],[beta(m.beta),30],[linear(m.cur,.7,2),25]]);
let valuation=weighted([[pe(m.pe),55],[pos==null?null:100-pos,45]]);if(h.p!=null)valuation=weighted([[valuation,60],[100-h.p,40]]);
const o=n(q.o),pc=n(q.pc),c=n(q.c),high=n(q.h),gapPct=o>0&&pc>0?(o-pc)/pc*100:null,down=gapPct!=null&&gapPct<=-1,width=down?pc-o:0,fill=down&&width>0&&c!=null?cl((c-o)/width*100):null,full=down&&high!=null&&high<pc,gapAtr=down&&m.atr>0?(o-pc)/m.atr:null;
const draw=dd==null?null:cl((Math.abs(Math.min(dd,0))-8)/27*100),gapMag=down?cl((Math.abs(gapPct)-1.5)/8.5*100):null,gapOpp=down&&quality>=60?weighted([[quality,30],[valuation,23],[gapMag,25],[full?90:55,10],[fill,12]]):null,weekly=weighted([[draw,60],[gapMag,40]]),tech=weighted([[pos==null?null:100-pos,55],[fill,35],[down?(c>=o?75:30):null,10]]);
const hard=(quality!=null&&quality<35)||(risk!=null&&risk<25)||(m.margin!=null&&m.margin<-10&&m.rev!=null&&m.rev<0),focus=weighted([[quality,30],[valuation,20],[growth,16],[weekly,20],[risk,10],[gapOpp,4]]),prev=db.entries[t]||{},pin=!!prev.manualPin;
let state=prev.state||'UNIVERSE',now=Date.now();if(activeContext(t))state='ACTIVE';else if(hard)state=pin?'WATCH':'UNIVERSE';else if(state==='FOCUS'&&prev.minimumStayUntil>now)state='FOCUS';else if((focus||0)>=ENTER)state='FOCUS';else if(state==='FOCUS'&&(focus||0)>=STAY)state='FOCUS';else if(state==='FOCUS')state='COOLDOWN';else if(prev.cooldownUntil>now)state='COOLDOWN';else if(gapOpp>=70&&quality>=70)state='WATCH';else if((focus||0)>=70)state='WATCH';else if((focus||0)>=55)state='CANDIDATE';else state='UNIVERSE';if(pin&&state==='UNIVERSE')state='WATCH';
const reasons=[];if(quality>=75)reasons.push('QUALITY_STRONG');if(growth>=65)reasons.push('GROWTH_POSITIVE');if(h.p!=null&&h.p<=15)reasons.push('VALUATION_HISTORIC_LOW');else if(valuation>=70)reasons.push('VALUATION_ATTRACTIVE_PROXY');if(dd<=-25)reasons.push('DRAWDOWN_EXTREME');else if(dd<=-15)reasons.push('DRAWDOWN_DEEP');if(down&&gapOpp>=70)reasons.push('QUALITY_GAP_DOWN');if(full)reasons.push('GAP_FULL_SESSION');if(fill>=20&&fill<100)reasons.push('GAP_RECLAIM_STARTED');if(fill>=50&&fill<100)reasons.push('GAP_FILL_50');reasons.push(hard?'STRUCTURAL_DAMAGE_RISK':'RISK_GATE_PASSED');if(h.status==='WARMING_UP')reasons.push('DELTA_HISTORY_WARMING_UP');
const entered=state==='FOCUS'&&prev.state!=='FOCUS',left=state==='COOLDOWN'&&prev.state==='FOCUS';return{ticker:t,name:item.name||t,state,manualPin:pin,alertLevel:prev.alertLevel||'WATCH',focusScore:focus,qualityScore:quality,valuationScore:valuation,growthScore:growth,weeklyRelevance:weekly,technicalReadiness:tech,riskScore:risk,gapOpportunity:gapOpp,price,drawdown:dd,rangePosition:pos,metrics:m,gap:{down,gapPct,gapAtr,fillProgress:fill,fullOpen:full,open:o,previousClose:pc,current:c},hardRisk:hard,reasons,historyStatus:h.status,historyCount:h.count,valuationPercentile:h.p,updatedAt:new Date().toISOString(),enteredAt:entered?new Date().toISOString():(prev.enteredAt||null),minimumStayUntil:entered?now+MIN_STAY:(prev.minimumStayUntil||0),cooldownUntil:left?now+COOLDOWN:(prev.cooldownUntil||0)}}
const labels={QUALITY_STRONG:'Unternehmensqualität stark',GROWTH_POSITIVE:'Wachstum positiv',VALUATION_HISTORIC_LOW:'Bewertung historisch niedrig',VALUATION_ATTRACTIVE_PROXY:'Bewertung und Kurslage attraktiv',DRAWDOWN_EXTREME:'Extremer Drawdown',DRAWDOWN_DEEP:'Deutlicher Drawdown',QUALITY_GAP_DOWN:'Quality Gap Opportunity',GAP_FULL_SESSION:'Gap vollständig offen',GAP_RECLAIM_STARTED:'Gap-Rückeroberung begonnen',GAP_FILL_50:'Gap mindestens 50 % gefüllt',STRUCTURAL_DAMAGE_RISK:'Risk Gate blockiert',RISK_GATE_PASSED:'Risk Gate bestanden',DELTA_HISTORY_WARMING_UP:'Verlauf wird aufgebaut'};
const cls=s=>s==='ACTIVE'||s==='FOCUS'?'good':s==='WATCH'?'mid':s==='COOLDOWN'?'warn':'neutral';
function styles(){if($('#senseisFocusStyles'))return;const x=document.createElement('style');x.id='senseisFocusStyles';x.textContent=`.focus-tools{display:flex;gap:8px}.focus-btn{min-height:47px;padding:0 13px;border:1px solid #3b4552;border-radius:13px;background:#12161c;color:#fff;font-weight:900}.focus-btn.main{color:#30d158;border-color:rgba(48,209,88,.45)}.focus-panel{margin:0 0 12px;padding:14px;border:1px solid #343c48;border-radius:17px;background:#0b0e12}.focus-panel[hidden]{display:none}.focus-head{display:flex;justify-content:space-between;gap:10px}.focus-head h3{margin:0}.focus-muted{color:#8c95a3;font-size:10px;line-height:1.45}.focus-list{display:grid;gap:7px;margin-top:10px}.focus-row{display:grid;grid-template-columns:1fr auto;gap:8px;padding:10px;border:1px solid #252b34;border-radius:12px;background:#12161c;cursor:pointer}.focus-row strong{font-size:12px}.focus-row small{display:block;color:#8c95a3;margin-top:3px}.focus-score{font-size:20px;font-weight:900}.focus-card{grid-column:1/-1;border-color:rgba(48,209,88,.25)!important}.focus-top{display:flex;justify-content:space-between;gap:12px}.focus-big{font-size:32px;font-weight:950}.focus-metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:11px}.focus-metric{padding:9px;border:1px solid #252b34;border-radius:10px;background:#12161c}.focus-metric span{display:block;color:#8c95a3;font-size:8px}.focus-reasons{display:flex;flex-wrap:wrap;gap:6px;margin-top:10px}.focus-reason{padding:5px 7px;border:1px solid #343c48;border-radius:999px;font-size:8px}.focus-gap{margin-top:11px;padding:10px;border:1px solid #343c48;border-radius:11px;background:#10151b}.focus-track{height:8px;margin-top:7px;border-radius:99px;background:#252b34;overflow:hidden}.focus-track div{height:100%;background:#fff}.focus-small,.focus-select{min-height:34px;border:1px solid #343c48;border-radius:10px;background:#151a21;color:#fff;padding:0 9px;font-size:10px;font-weight:900}@media(max-width:620px){.si-toolbar{grid-template-columns:1fr!important}.focus-tools{display:grid;grid-template-columns:1fr 1fr}.focus-metrics{grid-template-columns:1fr 1fr}.focus-top{display:block}}`;document.head.appendChild(x)}
function current(){return sym($('#siSymbol')?.value||localStorage.getItem(SEL)||'')}
function nameOf(t){const o=$$('#siSymbol option').find(x=>sym(x.value)===t);return o?.textContent?.split('—').slice(1).join('—').trim()||t}
function pin(){const t=current();if(!t)return;const e=db.entries[t]||{ticker:t,name:nameOf(t),state:'WATCH',focusScore:null,alertLevel:'WATCH'};e.manualPin=!e.manualPin;if(e.manualPin&&e.state==='UNIVERSE')e.state='WATCH';db.entries[t]=e;save();render()}
function alertLevel(t,v){if(db.entries[t]){db.entries[t].alertLevel=v;save();render()}}
function select(t){const s=$('#siSymbol'),o=s&&[...s.options].find(x=>sym(x.value)===t);if(!o)return;s.value=o.value;s.dispatchEvent(new Event('change',{bubbles:true}));open=false;render()}
function render(){if(paintBusy)return;paintBusy=true;requestAnimationFrame(()=>paintBusy=false);const tb=$('#view-stocks .si-toolbar');if(!tb)return;let tools=$('#focusTools');if(!tools){tools=document.createElement('div');tools.id='focusTools';tools.className='focus-tools';tools.innerHTML='<button id="focusToggle" class="focus-btn main">🎯 Fokusliste</button><button id="focusPin" class="focus-btn">☆ Fixieren</button>';tb.appendChild(tools);$('#focusToggle').onclick=()=>{open=!open;render()};$('#focusPin').onclick=pin}let panel=$('#focusPanel');if(!panel){panel=document.createElement('section');panel.id='focusPanel';panel.className='focus-panel';tb.insertAdjacentElement('afterend',panel)}panel.hidden=!open;const list=Object.values(db.entries).filter(e=>e.manualPin||['ACTIVE','FOCUS','WATCH','CANDIDATE','COOLDOWN'].includes(e.state)).sort((a,b)=>({ACTIVE:5,FOCUS:4,WATCH:3,CANDIDATE:2,COOLDOWN:1}[b.state]||0)-({ACTIVE:5,FOCUS:4,WATCH:3,CANDIDATE:2,COOLDOWN:1}[a.state]||0)||(b.focusScore??-1)-(a.focusScore??-1)).slice(0,20);panel.innerHTML=`<div class="focus-head"><div><h3>🎯 Bot-generierte Fokusliste</h3><div class="focus-muted">Qualität, Bewertung, Wachstum, Drawdown, Risiko und Quality-Gap-Chancen. Eintritt ab ${ENTER}, Verbleib ab ${STAY}.</div></div><div><button id="focusScan" class="focus-small">${running?'Scan läuft …':'Fokus-Scan starten'}</button>${running?'<button id="focusStop" class="focus-small">Stop</button>':''}</div></div><div class="focus-muted" style="margin-top:7px">${db.lastScan?'Letzter Scan vor '+Math.round((Date.now()-db.lastScan)/60000)+' Min.':'Noch kein Scan'}</div><div class="focus-list">${list.length?list.map(e=>`<div class="focus-row" data-f="${esc(e.ticker)}"><div><strong>${e.manualPin?'★ ':''}${esc(e.ticker)} · ${esc(e.name)}</strong><small><span class="si-chip ${cls(e.state)}" style="margin:0 6px 0 0">${e.state}</span>${(e.reasons||[]).slice(0,2).map(x=>labels[x]||x).join(' · ')}</small></div><div class="focus-score">${e.focusScore??'—'}</div></div>`).join(''):'<div class="focus-muted">Scan starten oder Aktie fixieren.</div>'}</div>`;$$('[data-f]').forEach(x=>x.onclick=()=>select(x.dataset.f));$('#focusScan')?.addEventListener('click',scan);$('#focusStop')?.addEventListener('click',()=>stop=true);
const t=current(),e=db.entries[t];$('#focusPin')?.replaceChildren(document.createTextNode(e?.manualPin?'★ Fixiert':'☆ Fixieren'));const grid=$('#view-stocks #siContent .si-grid');if(!grid)return;let card=$('#focusCard');if(!card){card=document.createElement('section');card.id='focusCard';card.className='si-card full focus-card';grid.prepend(card)}if(!e){card.innerHTML='<div class="si-ey">FOCUS ENGINE</div><h3>Daten werden aufgebaut</h3><div class="focus-muted">Fokus-Scan starten. Fehlende Historie wird nicht als neutral gewertet.</div>';return}const g=e.gap||{},gap=g.down?`<div class="focus-gap"><div class="focus-head"><div><strong>Quality Gap Opportunity</strong><div class="focus-muted">Gap ${pct(g.gapPct,1)}${g.gapAtr!=null?' · '+fmt(g.gapAtr,2)+' ATR':' · ATR noch nicht verfügbar'}</div></div><span class="si-chip ${e.gapOpportunity>=70?'good':'mid'}" style="margin:0">${e.gapOpportunity??'—'} / 100</span></div><div class="focus-muted" style="margin-top:6px">Rückeroberung ${fmt(g.fillProgress,0)} % · ${g.fullOpen?'Gap noch vollständig offen':'Gap teilweise zurückerobert'}</div><div class="focus-track"><div style="width:${cl(g.fillProgress||0)}%"></div></div></div>`:'';card.innerHTML=`<div class="focus-top"><div><div class="si-ey">FOCUS ENGINE · ${esc(t)}</div><h3 style="margin:5px 0">${e.state} · ${e.focusScore??'—'} / 100</h3><div class="focus-muted">Qualität und Risiko werden getrennt von der aktuellen Wochenrelevanz bewertet.</div></div><div><div class="focus-big">${e.focusScore??'—'}</div><button id="focusCardPin" class="focus-small">${e.manualPin?'★ Fixiert':'☆ Fixieren'}</button><select id="focusAlert" class="focus-select"><option>FULL</option><option>CONTEXT</option><option>WATCH</option><option>MUTE</option></select></div></div><div class="focus-metrics">${[['QUALITÄT',e.qualityScore],['BEWERTUNG',e.valuationScore],['WACHSTUM',e.growthScore],['WOCHENRELEVANZ',e.weeklyRelevance],['TECHNISCHE BEREITSCHAFT',e.technicalReadiness],['RISIKOQUALITÄT',e.riskScore]].map(([a,b])=>`<div class="focus-metric"><span>${a}</span><strong>${b??'—'}</strong></div>`).join('')}</div>${gap}<div class="focus-reasons">${(e.reasons||[]).slice(0,7).map(x=>`<span class="focus-reason">${esc(labels[x]||x)}</span>`).join('')}</div><div class="focus-muted" style="margin-top:9px">Drawdown ${pct(e.drawdown,1)} · 52W-Position ${fmt(e.rangePosition,0)} % · Historie ${e.historyStatus}${e.historyStatus==='WARMING_UP'?' '+e.historyCount+'/20':' · Perzentil '+e.valuationPercentile}. Ein Gap ist ein Signal, kein Schließungsversprechen.</div>`;$('#focusCardPin').onclick=pin;const al=$('#focusAlert');al.value=e.alertLevel||'WATCH';al.onchange=()=>alertLevel(t,al.value)}
async function json(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error('HTTP_'+r.status);return r.json()}
async function universe(){try{const r=await fetch('./focus-universe.json',{cache:'no-store'}),x=await r.json();return x.tickers||[]}catch{return[]}}
async function scan(){if(running)return;const key=String(localStorage.getItem(FK)||'').trim();if(!key||key==='SENSEIS_DAX_ONLY'){alert('Finnhub-Key fehlt. Im Trade Calculator unter ⚙️ API speichern.');return}const list=await universe();if(!list.length){alert('Fokus-Universum nicht verfügbar.');return}running=true;stop=false;open=true;render();for(let i=0;i<list.length&&!stop;i++){const item=list[i],t=sym(item.symbol);try{const [q,m]=await Promise.all([json(`https://finnhub.io/api/v1/quote?symbol=${encodeURIComponent(t)}&token=${encodeURIComponent(key)}`),json(`https://finnhub.io/api/v1/stock/metric?symbol=${encodeURIComponent(t)}&metric=all&token=${encodeURIComponent(key)}`)]);const e=score(item,q,m);db.entries[t]=e;snapshot(e);save()}catch(err){db.entries[t]={...(db.entries[t]||{}),ticker:t,name:item.name||t,state:db.entries[t]?.state||'UNIVERSE',manualPin:!!db.entries[t]?.manualPin,alertLevel:db.entries[t]?.alertLevel||'WATCH',lastError:String(err.message||err)}}render();if(i<list.length-1&&!stop)await new Promise(r=>setTimeout(r,DELAY))}db.lastScan=Date.now();save();running=false;stop=false;render()}
function boot(){styles();const root=$('#view-stocks');if(!root)return;new MutationObserver(()=>{if(!paintBusy){clearTimeout(timer);timer=setTimeout(render,80)}}).observe(root,{subtree:true,childList:true});document.addEventListener('change',e=>{if(e.target?.id==='siSymbol')setTimeout(render,100)});setTimeout(render,150)}
window.SenSeiSFocusEngine={version:V,scan,get:t=>db.entries[sym(t)]||null,list:()=>Object.values(db.entries),evaluate:(item,quote,metric)=>score(item,quote,metric)};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();